name: Build Multi-Platform Binaries

on:
  push:
  pull_request:
    branches: ["main"]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Build for Linux
        run: cargo build --release
      - name: Upload Linux binary
        uses: actions/upload-artifact@v4
        with:
          name: sputnik-indexer-linux
          path: target/release/sputnik-indexer

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Build for macOS ARM64
        run: cargo build --release
      - name: Upload macOS binary
        uses: actions/upload-artifact@v4
        with:
          name: sputnik-indexer-macos-arm64
          path: target/release/sputnik-indexer
