name: Build Linux Binary

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Build for Linux
        run: cargo build --release
      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: sputnik-indexer
          path: target/release/sputnik-indexer
